/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeLayoutRouteImport } from './routes/_homeLayout'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as HomeLayoutIndexRouteImport } from './routes/_homeLayout/index'
import { Route as HomeLayoutServerTitleRouteImport } from './routes/_homeLayout/$serverTitle'
import { Route as AuthLayoutRegisterRouteImport } from './routes/_authLayout/register'
import { Route as AuthLayoutLoginRouteImport } from './routes/_authLayout/login'
import { Route as HomeLayoutServerTitleChatRoomIdRouteImport } from './routes/_homeLayout/$serverTitle.$chatRoomId'
import { Route as HomeLayoutServerTitleBoardBoardTitleRouteImport } from './routes/_homeLayout/$serverTitle/board/$boardTitle'

const HomeLayoutRoute = HomeLayoutRouteImport.update({
  id: '/_homeLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutIndexRoute = HomeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)
const HomeLayoutServerTitleRoute = HomeLayoutServerTitleRouteImport.update({
  id: '/$serverTitle',
  path: '/$serverTitle',
  getParentRoute: () => HomeLayoutRoute,
} as any)
const AuthLayoutRegisterRoute = AuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const HomeLayoutServerTitleChatRoomIdRoute =
  HomeLayoutServerTitleChatRoomIdRouteImport.update({
    id: '/$chatRoomId',
    path: '/$chatRoomId',
    getParentRoute: () => HomeLayoutServerTitleRoute,
  } as any)
const HomeLayoutServerTitleBoardBoardTitleRoute =
  HomeLayoutServerTitleBoardBoardTitleRouteImport.update({
    id: '/board/$boardTitle',
    path: '/board/$boardTitle',
    getParentRoute: () => HomeLayoutServerTitleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLayoutLoginRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/$serverTitle': typeof HomeLayoutServerTitleRouteWithChildren
  '/': typeof HomeLayoutIndexRoute
  '/$serverTitle/$chatRoomId': typeof HomeLayoutServerTitleChatRoomIdRoute
  '/$serverTitle/board/$boardTitle': typeof HomeLayoutServerTitleBoardBoardTitleRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLayoutLoginRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/$serverTitle': typeof HomeLayoutServerTitleRouteWithChildren
  '/': typeof HomeLayoutIndexRoute
  '/$serverTitle/$chatRoomId': typeof HomeLayoutServerTitleChatRoomIdRoute
  '/$serverTitle/board/$boardTitle': typeof HomeLayoutServerTitleBoardBoardTitleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_homeLayout': typeof HomeLayoutRouteWithChildren
  '/_authLayout/login': typeof AuthLayoutLoginRoute
  '/_authLayout/register': typeof AuthLayoutRegisterRoute
  '/_homeLayout/$serverTitle': typeof HomeLayoutServerTitleRouteWithChildren
  '/_homeLayout/': typeof HomeLayoutIndexRoute
  '/_homeLayout/$serverTitle/$chatRoomId': typeof HomeLayoutServerTitleChatRoomIdRoute
  '/_homeLayout/$serverTitle/board/$boardTitle': typeof HomeLayoutServerTitleBoardBoardTitleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/$serverTitle'
    | '/'
    | '/$serverTitle/$chatRoomId'
    | '/$serverTitle/board/$boardTitle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/$serverTitle'
    | '/'
    | '/$serverTitle/$chatRoomId'
    | '/$serverTitle/board/$boardTitle'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_homeLayout'
    | '/_authLayout/login'
    | '/_authLayout/register'
    | '/_homeLayout/$serverTitle'
    | '/_homeLayout/'
    | '/_homeLayout/$serverTitle/$chatRoomId'
    | '/_homeLayout/$serverTitle/board/$boardTitle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_homeLayout': {
      id: '/_homeLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homeLayout/': {
      id: '/_homeLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutIndexRouteImport
      parentRoute: typeof HomeLayoutRoute
    }
    '/_homeLayout/$serverTitle': {
      id: '/_homeLayout/$serverTitle'
      path: '/$serverTitle'
      fullPath: '/$serverTitle'
      preLoaderRoute: typeof HomeLayoutServerTitleRouteImport
      parentRoute: typeof HomeLayoutRoute
    }
    '/_authLayout/register': {
      id: '/_authLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthLayoutRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_homeLayout/$serverTitle/$chatRoomId': {
      id: '/_homeLayout/$serverTitle/$chatRoomId'
      path: '/$chatRoomId'
      fullPath: '/$serverTitle/$chatRoomId'
      preLoaderRoute: typeof HomeLayoutServerTitleChatRoomIdRouteImport
      parentRoute: typeof HomeLayoutServerTitleRoute
    }
    '/_homeLayout/$serverTitle/board/$boardTitle': {
      id: '/_homeLayout/$serverTitle/board/$boardTitle'
      path: '/board/$boardTitle'
      fullPath: '/$serverTitle/board/$boardTitle'
      preLoaderRoute: typeof HomeLayoutServerTitleBoardBoardTitleRouteImport
      parentRoute: typeof HomeLayoutServerTitleRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutRegisterRoute: typeof AuthLayoutRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutRegisterRoute: AuthLayoutRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface HomeLayoutServerTitleRouteChildren {
  HomeLayoutServerTitleChatRoomIdRoute: typeof HomeLayoutServerTitleChatRoomIdRoute
  HomeLayoutServerTitleBoardBoardTitleRoute: typeof HomeLayoutServerTitleBoardBoardTitleRoute
}

const HomeLayoutServerTitleRouteChildren: HomeLayoutServerTitleRouteChildren = {
  HomeLayoutServerTitleChatRoomIdRoute: HomeLayoutServerTitleChatRoomIdRoute,
  HomeLayoutServerTitleBoardBoardTitleRoute:
    HomeLayoutServerTitleBoardBoardTitleRoute,
}

const HomeLayoutServerTitleRouteWithChildren =
  HomeLayoutServerTitleRoute._addFileChildren(
    HomeLayoutServerTitleRouteChildren,
  )

interface HomeLayoutRouteChildren {
  HomeLayoutServerTitleRoute: typeof HomeLayoutServerTitleRouteWithChildren
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutServerTitleRoute: HomeLayoutServerTitleRouteWithChildren,
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
