/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeLayoutRouteImport } from './routes/_homeLayout'
import { Route as HomeLayoutIndexRouteImport } from './routes/_homeLayout/index'
import { Route as HomeLayoutServerTitleRouteImport } from './routes/_homeLayout/$serverTitle'
import { Route as HomeLayoutServerTitleChatRoomIdRouteImport } from './routes/_homeLayout/$serverTitle.$chatRoomId'
import { Route as HomeLayoutServerTitleChatChatRoomIdRouteImport } from './routes/_homeLayout/$serverTitle/chat/$chatRoomId'
import { Route as HomeLayoutServerTitleBoardBoardIdRouteImport } from './routes/_homeLayout/$serverTitle/board/$boardId'

const HomeLayoutRoute = HomeLayoutRouteImport.update({
  id: '/_homeLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutIndexRoute = HomeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)
const HomeLayoutServerTitleRoute = HomeLayoutServerTitleRouteImport.update({
  id: '/$serverTitle',
  path: '/$serverTitle',
  getParentRoute: () => HomeLayoutRoute,
} as any)
const HomeLayoutServerTitleChatRoomIdRoute =
  HomeLayoutServerTitleChatRoomIdRouteImport.update({
    id: '/$chatRoomId',
    path: '/$chatRoomId',
    getParentRoute: () => HomeLayoutServerTitleRoute,
  } as any)
const HomeLayoutServerTitleChatChatRoomIdRoute =
  HomeLayoutServerTitleChatChatRoomIdRouteImport.update({
    id: '/chat/$chatRoomId',
    path: '/chat/$chatRoomId',
    getParentRoute: () => HomeLayoutServerTitleRoute,
  } as any)
const HomeLayoutServerTitleBoardBoardIdRoute =
  HomeLayoutServerTitleBoardBoardIdRouteImport.update({
    id: '/board/$boardId',
    path: '/board/$boardId',
    getParentRoute: () => HomeLayoutServerTitleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$serverTitle': typeof HomeLayoutServerTitleRouteWithChildren
  '/': typeof HomeLayoutIndexRoute
  '/$serverTitle/$chatRoomId': typeof HomeLayoutServerTitleChatRoomIdRoute
  '/$serverTitle/board/$boardId': typeof HomeLayoutServerTitleBoardBoardIdRoute
  '/$serverTitle/chat/$chatRoomId': typeof HomeLayoutServerTitleChatChatRoomIdRoute
}
export interface FileRoutesByTo {
  '/$serverTitle': typeof HomeLayoutServerTitleRouteWithChildren
  '/': typeof HomeLayoutIndexRoute
  '/$serverTitle/$chatRoomId': typeof HomeLayoutServerTitleChatRoomIdRoute
  '/$serverTitle/board/$boardId': typeof HomeLayoutServerTitleBoardBoardIdRoute
  '/$serverTitle/chat/$chatRoomId': typeof HomeLayoutServerTitleChatChatRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_homeLayout': typeof HomeLayoutRouteWithChildren
  '/_homeLayout/$serverTitle': typeof HomeLayoutServerTitleRouteWithChildren
  '/_homeLayout/': typeof HomeLayoutIndexRoute
  '/_homeLayout/$serverTitle/$chatRoomId': typeof HomeLayoutServerTitleChatRoomIdRoute
  '/_homeLayout/$serverTitle/board/$boardId': typeof HomeLayoutServerTitleBoardBoardIdRoute
  '/_homeLayout/$serverTitle/chat/$chatRoomId': typeof HomeLayoutServerTitleChatChatRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$serverTitle'
    | '/'
    | '/$serverTitle/$chatRoomId'
    | '/$serverTitle/board/$boardId'
    | '/$serverTitle/chat/$chatRoomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$serverTitle'
    | '/'
    | '/$serverTitle/$chatRoomId'
    | '/$serverTitle/board/$boardId'
    | '/$serverTitle/chat/$chatRoomId'
  id:
    | '__root__'
    | '/_homeLayout'
    | '/_homeLayout/$serverTitle'
    | '/_homeLayout/'
    | '/_homeLayout/$serverTitle/$chatRoomId'
    | '/_homeLayout/$serverTitle/board/$boardId'
    | '/_homeLayout/$serverTitle/chat/$chatRoomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_homeLayout': {
      id: '/_homeLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homeLayout/': {
      id: '/_homeLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutIndexRouteImport
      parentRoute: typeof HomeLayoutRoute
    }
    '/_homeLayout/$serverTitle': {
      id: '/_homeLayout/$serverTitle'
      path: '/$serverTitle'
      fullPath: '/$serverTitle'
      preLoaderRoute: typeof HomeLayoutServerTitleRouteImport
      parentRoute: typeof HomeLayoutRoute
    }
    '/_homeLayout/$serverTitle/$chatRoomId': {
      id: '/_homeLayout/$serverTitle/$chatRoomId'
      path: '/$chatRoomId'
      fullPath: '/$serverTitle/$chatRoomId'
      preLoaderRoute: typeof HomeLayoutServerTitleChatRoomIdRouteImport
      parentRoute: typeof HomeLayoutServerTitleRoute
    }
    '/_homeLayout/$serverTitle/chat/$chatRoomId': {
      id: '/_homeLayout/$serverTitle/chat/$chatRoomId'
      path: '/chat/$chatRoomId'
      fullPath: '/$serverTitle/chat/$chatRoomId'
      preLoaderRoute: typeof HomeLayoutServerTitleChatChatRoomIdRouteImport
      parentRoute: typeof HomeLayoutServerTitleRoute
    }
    '/_homeLayout/$serverTitle/board/$boardId': {
      id: '/_homeLayout/$serverTitle/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/$serverTitle/board/$boardId'
      preLoaderRoute: typeof HomeLayoutServerTitleBoardBoardIdRouteImport
      parentRoute: typeof HomeLayoutServerTitleRoute
    }
  }
}

interface HomeLayoutServerTitleRouteChildren {
  HomeLayoutServerTitleChatRoomIdRoute: typeof HomeLayoutServerTitleChatRoomIdRoute
  HomeLayoutServerTitleBoardBoardIdRoute: typeof HomeLayoutServerTitleBoardBoardIdRoute
  HomeLayoutServerTitleChatChatRoomIdRoute: typeof HomeLayoutServerTitleChatChatRoomIdRoute
}

const HomeLayoutServerTitleRouteChildren: HomeLayoutServerTitleRouteChildren = {
  HomeLayoutServerTitleChatRoomIdRoute: HomeLayoutServerTitleChatRoomIdRoute,
  HomeLayoutServerTitleBoardBoardIdRoute:
    HomeLayoutServerTitleBoardBoardIdRoute,
  HomeLayoutServerTitleChatChatRoomIdRoute:
    HomeLayoutServerTitleChatChatRoomIdRoute,
}

const HomeLayoutServerTitleRouteWithChildren =
  HomeLayoutServerTitleRoute._addFileChildren(
    HomeLayoutServerTitleRouteChildren,
  )

interface HomeLayoutRouteChildren {
  HomeLayoutServerTitleRoute: typeof HomeLayoutServerTitleRouteWithChildren
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutServerTitleRoute: HomeLayoutServerTitleRouteWithChildren,
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
